language: ruby
rvm:
  - 2.6.0

before_script:
 - chmod +x ./_scripts/build
script: ./_scripts/build

git:
  submodules: true

branches:
  only:
    - dev

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - JEKYLL_ENV=production

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false

cache: bundler

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    fqdn: klez.me
    local_dir: _site/
    deployment-file: true
    on:
      branch: dev
    target-branch: master
