os: linux
language: ruby
rvm:
  - 2.6.0

before_script:
 - chmod +x ./_scripts/build
script: ./_scripts/build

git:
  submodules: true

branches:
  only:
    - dev

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - JEKYLL_ENV=production

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler

deploy:
    provider: pages
    skip_cleanup: true
    token: $GITHUB_TOKEN
    keep_history: true
    fqdn: klez.me
    local_dir: _site/
    deployment_file: true
    on:
      branch: dev
    target_branch: master
