timezone: Europe/Rome
title: Alessandro 'kLeZ' Accardo personal website
description: >-
    This is the personal website of an Italian developer once called 'kLeZ'.
baseurl: ""
url: "https://klez.me"
copyright: Copyright © Alessandro 'kLeZ' Accardo 2019

author:
    name: Alessandro 'kLeZ' Accardo
    brand: kLeZ
    email: klez@pm.me
    social:
        - name: twitter
          username: kLeZhAcK
          display: ""
          icon:
              type: fa
              value: fa-twitter
        - name: github
          username: kLeZ
          display: ""
          icon:
              type: fa
              value: fa-github
        - name: rss
          instance: /feed.xml
          username: ""
          display: ""
          icon:
              type: fa
              value: fa-rss

rss: RSS feed

sass:
    sass_dir: _sass

include:
    - _pages

defaults:
    - scope:
          path: ""
      values:
          author: Alessandro 'kLeZ' Accardo
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"

excerpt_separator: "<!--more-->"

plugins:
    - jekyll-feed
# Defaults. IF you want to change the exclude make sure you keep those sane defaults
# exclude:
#     - Gemfile
#     - Gemfile.lock
#     - node_modules
#     - vendor/bundle/
#     - vendor/cache/
#     - vendor/gems/
#     - vendor/ruby/
