timezone: Europe/Rome
title: Alessandro 'kLeZ' Accardo personal website
description: >-
    This is the personal website of an Italian developer once called 'kLeZ'.
baseurl: ""
url: "https://klez.me"
copyright: Copyright © Alessandro 'kLeZ' Accardo 2019
build:
    server: https://travis-ci.org/kLeZ/kLeZ.github.io
    status: https://travis-ci.org/kLeZ/kLeZ.github.io.svg?branch=dev

author:
    name: Alessandro 'kLeZ' Accardo
    brand: kLeZ
    email: klez@pm.me
    social:
        - name: twitter
          username: kLeZhAcK
          display:
          icon:
              type: fa
              value: fab fa-twitter
        - name: github
          username: kLeZ
          display:
          icon:
              type: fa
              value: fab fa-github
        - name: rss
          instance: /feed.xml
          username:
          display:
          icon:
              type: fa
              value: fa fa-rss
        - name: email
          instance: "mailto:"
          username: klez@pm.me
          display:
          icon:
              type: fa
              value: fa fa-envelope

sass:
    sass_dir: _sass

include:
    - _pages

defaults:
    - scope:
          path: ""
      values:
          author: kLeZ
          header_background_url: /assets/img/home-bg.jpg
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"

show_excerpts: true
excerpt_separator: <!--more-->

jekyll_tidy:
    compress_html: false

plugins:
    - jekyll-feed
    - jekyll-tidy

# Defaults. IF you want to change the exclude make sure you keep those sane defaults
# exclude:
#     - Gemfile
#     - Gemfile.lock
#     - node_modules
#     - vendor/bundle/
#     - vendor/cache/
#     - vendor/gems/
#     - vendor/ruby/
