timezone: Europe/Rome
title: Alessandro 'kLeZ' Accardo personal website
description: >-
    This is the personal website of an Italian developer once called 'kLeZ'.
baseurl: ""
url: https://klez.me
copyright: Copyright © Alessandro 'kLeZ' Accardo 2019
repo: https://github.com/kLeZ/kLeZ.github.io
build:
    server: https://travis-ci.org/kLeZ/kLeZ.github.io
    status: https://travis-ci.org/kLeZ/kLeZ.github.io.svg?branch=dev

twitter:
    username: kLeZhAcK
    card: summary

comments:
    enabled: true
    type: staticman
    post_url: https://klez-commenter.herokuapp.com/v2/entry/kLeZ/kLeZ.github.io/dev/comments/
    avatar_provider: gravatar

sass:
    sass_dir: _sass
    style: compressed

include:
    - _pages

defaults:
    - scope:
          path: ""
      values:
          author:
              name: kLeZ
              twitter: kLeZhAcK
          header_background_url: /assets/img/home-bg.jpg
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"
          permalink: /:year/:month/:day/:title/
          post: true

show_excerpts: true
excerpt_separator: "{% include more.html %}"

markdown: kramdown
highlighter: rouge
katex:
    js_path: "assets/katex"
    rendering_options:
        throw_error: true
        error_color: "#cc0000"

goat-counter:
  count-url: https://klez.goatcounter.com/count
  code: klez
  production-url: klez.me

jekyll_tidy:
    compress_html: false

emoji:
    src: "/assets/img"

plugins:
    - jekyll-feed
    - jekyll-tidy
    - jekyll-katex
    - liquid_reading_time
    - liquid_pluralize
    - jekyll-git_metadata
    - jekyll-seo-tag
    - jemoji
    - jekyll-postfiles

# Defaults. IF you want to change the exclude make sure you keep those sane defaults
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - blog-vector-icon-27.jpg
    - staticman.yml
