timezone: Europe/Rome
title: Alessandro 'kLeZ' Accardo personal website
description: >-
    This is the personal website of an Italian developer once called 'kLeZ'.
baseurl: ""
url: "https://klez.me"
copyright: Copyright © Alessandro 'kLeZ' Accardo 2019
build:
    server: https://travis-ci.org/kLeZ/kLeZ.github.io
    status: https://travis-ci.org/kLeZ/kLeZ.github.io.svg?branch=dev

sass:
    sass_dir: _sass

include:
    - _pages

defaults:
    - scope:
          path: ""
      values:
          author: kLeZ
          header_background_url: /assets/img/home-bg.jpg
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"
          permalink: /:year/:month/:day/:title/

show_excerpts: true
excerpt_separator: <!--more-->

jekyll_tidy:
    compress_html: false

# Defaults. IF you want to change the exclude make sure you keep those sane defaults
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - blog-vector-icon-27.jpg
