#!/bin/bash
set -e # halt script on error

bundle exec jekyll doctor

if [[ $CI == "true" ]]; then
	tee _data/ci-status.yml <<EOF
last_commit:
    short_sha: $(echo ${COMMIT_SHA:-abcdef01} | cut -c 1-8)
    long_sha: ${COMMIT_SHA:-abcdef01abcdef01abcdef01abcdef01abcdef01}
    message: |- $(echo; echo -e "${COMMIT_MESSAGE}" | sed 's/^/        /')
build:
    number: ${BUILD_NUMBER:-0}
    id: ${BUILD_ID:-0}
    url: ${BUILD_WEB_URL:-https://example.org}
EOF
	echo -e "\n"
	bundle exec jekyll build
else
	bash ./_scripts/publish
	bash ./_scripts/emojis
	cat _data/ci-status.yml
	echo -e "\n"
	bundle exec jekyll build --drafts --trace
fi

bundle exec htmlproofer ./_site --disable-external
