#!/bin/bash
set -e # halt script on error

cat <<EOF > _data/travis.yml
commit:
    hash: ${TRAVIS_COMMIT:-abcdef01}
    message: "${TRAVIS_COMMIT_MESSAGE}"
    tag: ${TRAVIS_TAG:-0.1}
build:
    number: ${TRAVIS_BUILD_NUMBER:-0}
    id: ${TRAVIS_BUILD_ID:-0}
    url: ${TRAVIS_BUILD_WEB_URL:-https://example.org}
EOF

bundle exec jekyll build --drafts
bundle exec htmlproofer ./_site --disable-external
