#!/bin/bash

title="$@"
safe_title=$(echo $title | tr '[:upper:]' '[:lower:]' | iconv -f utf-8 -t ascii//translit | tr '[ \t]' '-' | tr -cd '[^a-z0-9-+_.]')
echo $safe_title

if [[ -n $safe_title ]]; then
	cp _templates/post.md _drafts/$safe_title.md
	sed -i "s/title: /title: \"$title\"/" _drafts/$safe_title.md
	$JEKYLL_EDITOR _drafts/$safe_title.md
fi
