#!/bin/bash

chmod +x _scripts/emojis
./_scripts/emojis

for f in `ls _drafts/*.md`;
do
	current_date="$(date '+%Y-%m-%d %H:%M:%S%:z')"
	sed -i "s/__CURRENT_DATE/${current_date}/" $f;
	sed -i "s/##date:/date:/" $f
	mv ${f} _posts/`date '+%Y-%m-%d'`-`basename ${f%.pub}`
done
