#!/bin/bash
# Esegue dalla radice del repo anche se invocato come 'publish' dal PATH.
cd "$(dirname "$(readlink -f "$0")")/.."

for f in `ls _drafts/*.draft`;
do
	current_date="$(date '+%Y-%m-%d %H:%M:%S%:z')"
	sed -i "s/__CURRENT_DATE/${current_date}/" $f;
	sed -i "s/##date:/date:/" $f
	mv ${f} _posts/`date '+%Y-%m-%d'`-`basename ${f%.draft}`
done
